spring.application.name=ArchivePlayer

spring.datasource.url=jdbc:postgresql://localhost:5432/archive_db
spring.datasource.username=postgres
spring.datasource.password=admin

server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.music.root-path=${MUSIC_ROOT_PATH:C:/Users/Nick/Desktop/MiniGame/archive/fma_medium}
app.music.default-duration-seconds=180

app.jwt.secret=${APP_JWT_SECRET:your-super-secret-jwt-key-change-me-in-production}
app.jwt.expiration-ms=86400000

ALLOWED_ORIGINS=${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}

spring.jpa.defer-datasource-initialization=true