# Local Development Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/fauxtify_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create-drop

app.jwt.secret=local_dev_only_super_long_secret_key_at_least_64_chars_long_1234567890abcdefghijklmnopqrstuvwxyz
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173

# Local File Path for Music
# Points to our new sample-music folder for local testing
app.music.root-path=sample-music